module.exports = {
  title: "kibeom",
  description: "Hello :) I'm a software engineer",
  author: "kibeom",
  // siteUrl: "https://devhudi.github.io/gatsby-starter-hoodie/",
  siteUrl: "https://kibeom-kim.github.io/",
  links: {
    github: "https://github.com/kibeom-kim",
    linkedIn: "https://linkedin.com",
    // facebook: "https://www.facebook.com",
    // twitter: "https://twitter.com",
    // x: "https://x.com",
    // instagram: "https://www.instagram.com",
    // medium: "https://medium.com",
    // blogger: "https://blogger.com",
    // email: "mailto:devhudi@gmail.com",
    // resume: "https://hudi.blog",
    // link: "https://hudi.blog",
  },
  useAbout: true,
  // See https://giscus.app/
  giscus: {
    repo: "kibeom-kim/kibeom-kim.github.io",
    repoId: "R_kgDOPqKnfg",
    category: "General",
    categoryId: "DIC_kwDOPqKnfs4Cu_hf",
    mapping: "pathname",
    strict: "0",
    reactionsEnabled: "1",
    inputPosition: "bottom",
    lang: "en",
  },
}
